### ISSUE TITLE
LICENSE VIOLATED

### ISSUE THREAD

**Issue by giuliocalzo** [neillturner/terraform-aws-lambda-es-cleanup#1]
Hi @neillturner 
are you aware that this repo is violating the original license of this code.

https://github.com/cloudreach/aws-lambda-es-cleanup/blob/master/LICENSE.md

can you please do a fork of the original repo and maintaining the original producer?

**Comment by neillturner** [comment]
I included your license. this is just a packaging of it for terraform so not really a fork. 
If you would like to take my terraform code and package your code and deploy to the terraform registry feel feel.
Just making it easier for people to use your code.
